[tool.pyright]
include = [
    "jobs",
]
typeCheckingMode = "strict"
reportUnnecessaryIsInstance = false
reportUnusedImport = "warning"
reportUnusedVariable = "warning"
reportUnusedFunction = "warning"
reportUnusedExpression = "warning"